# Generated by Django 4.1.6 on 2023-02-08 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 15, 8, 5, 53, 600558)
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
